services:
  app:
    build:
      context: ./Docker/PHP
      dockerfile: Dockerfile
      args:
        user: laraveluser
        uid: 1000
    container_name: keepcode_app
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - keepcode-network

  web:
    image: nginx:1.21-alpine
    container_name: keepcode_web
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - keepcode-network

  db:
    image: mariadb:10.5
    container_name: keepcode_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata-keepcode:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - keepcode-network

  redis:
    image: redis:alpine
    container_name: keepcode_redis
    ports:
      - "6379:6379"
    networks:
      - keepcode-network

volumes:
  dbdata-keepcode:

networks:
  keepcode-network: